# Generated by Django 4.2.10 on 2024-03-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newsletter'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='contact',
            table_comment=None,
        ),
    ]
