# Generated by Django 4.2.10 on 2024-03-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_contact_table_comment'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='contact',
            table_comment='Contact Table',
        ),
    ]
